pipeline {
     agent any
     stages {
         stage('clean up') {
            steps{
                sh(script: """
                    echo "clean up"
                    pwd
                    rm -rf *
                """)
                }
        }
        stage('Checkout') {
            steps {
                echo 'Checkout'
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'david-private-key-github', url: 'git@github.com:davidxy123/fair-play.git']]])
                sh "ls -lrt"
            }
        }
        stage('List all files') {
            steps{
                sh(script: """
                   echo "list files with tree view"
                   tree -lh
                """)
            }
        }
    }
}
