pipeline {
     agent any
     stages {
         stage('clean up') {
            steps{
                sh(script: """
                    ls
                    echo "clean up"
                    pwd
                    rm -rf *
                    mvn --version
                """)
                }
        }
        stage('test pipeline') {
            steps{
                sh(script: """
                   echo "check branch"
                   git branch
                   git branch -a
                   echo "check tags"
                   git tag -l
                   echo "find files"
                   ls -lrt
                   cd ./fair-play
                   ls
                   whoami
                   id
                   docker ps -a
                   docker images -a
                """)
            }
        }
    }
}
